### PR TITLE
Refactor & Bug Fixes

### LINKED ISSUE #37: Drain failure should not fail event
At the moment when drain fails, we fail the event.
This means we skip the ALB deregistration part if the drain fails.
It might still be relevant to try and drain target groups.

In case drain fails we should still attempt to deregister target groups

### PR DESCRIPTION
**Pull request by eytan-avisror**
Fixes #37, #34 
Contributes to #35 

This PR adds/modifies the following:
- Introduce AWS API Caching to help with throttling with concurrent terminations
- Implement custom waiters instead of using AWS waiters (to improve caching).
- Use `event.eventCompleted` to drop goroutines when an instance is abandoned (#34)
- Drain failure will no longer fails an event (#37)
- Structure improvements to improve performance, along with jitter/sleep changes
- Deregister sequentially before spawning waiters
- Fix conflict with event names (time may not be unique)

### CODE REVIEW

File: cmd/serve.go [hunk 1]
```diff
@@ -58,18 +59,20 @@ var serveCmd = &cobra.Command{
 		// argument validation
 		validate()
 		log.SetLevel(logLevel)
+		cacheCfg := cache.NewConfig(0 * time.Second)
```
Comment (kevdowney) [inline cmd/serve.go]:
```suggestion
		cacheCfg := cache.NewConfig(0 * time.Second)
```
Maybe there should be an enhancement later to configure this cache timeout?

File: cmd/serve.go [hunk 2]
```diff
@@ -141,27 +144,47 @@ func newKubernetesClient(localMode string) *kubernetes.Clientset {
...
 	config := aws.NewConfig().WithRegion(region)
 	config = config.WithCredentialsChainVerboseErrors(true)
 	config = request.WithRetryer(config, log.NewRetryLogger(DefaultRetryer))
 	sess, err := session.NewSession(config)
 	if err != nil {
 		log.Fatalf("failed to create elbv2 client, %v", err)
 	}
-
+	cache.AddCaching(sess, cacheCfg)
+	cacheCfg.SetCacheTTL("elasticloadbalancing", "DescribeTargetHealth", 180*time.Second)
```
Comment (kevdowney) [inline cmd/serve.go]: Recommend putting these TTL defaults as constants.

File: cmd/serve.go (hunk 1 above)
Comment (eytan-avisror) [reply cmd/serve.go]: This is a global config, individual cache TTLs are configured below

File: cmd/serve.go (hunk 2 above)
Comment (eytan-avisror) [reply cmd/serve.go]: +1 yep

File: pkg/service/elb.go [hunk 3]
```diff
@@ -1,38 +1,57 @@
...
+					return nil
+				}
+				break
+			}
+		}
+		if !found {
+			log.Debugf("instance %v not found in elb %v", instanceID, elbName)
+			return nil
+		}
+		log.Debugf("target %v is still deregistering from %v", instanceID, elbName)
```
Comment (davemasselink) [inline pkg/service/elb.go]: is there value in including the iteration number (`i`) and `MaxAttempts` in this debug msg?

ex:
```suggestion
		log.Debugf("target %v is still deregistering from %v (%v/%v)", instanceID, elbName, i, MaxAttempts)
```

File: pkg/service/elbv2.go [hunk 4]
```diff
@@ -1,40 +1,57 @@
...
+					return nil
+				}
+				break
+			}
+		}
+		if !found {
+			log.Debugf("target %v not found in target group %v", instanceID, arn)
+			return nil
+		}
+		log.Debugf("target %v is still deregistering from %v", instanceID, arn)
```
Comment (davemasselink) [inline pkg/service/elbv2.go]: same comment as in `elb.go` file
```suggestion
		log.Debugf("target %v is still deregistering from %v (%v/%v)", instanceID, arn, i, MaxAttempts)
```

File: pkg/service/server.go [hunk 5]
```diff
@@ -2,6 +2,7 @@ package service
 
 import (
 	"fmt"
+	"github.com/pkg/errors"
```
Comment (davemasselink) [inline pkg/service/server.go]: nit: move import down to other `github.com` imports

File: pkg/service/server.go [hunk 6]
```diff
@@ -369,10 +372,28 @@ func (mgr *Manager) drainLoadbalancerTarget(event *LifecycleEvent) error {
...
+	err := labelNode(kubeClient, ctx.KubectlLocalPath, node.Name, ExcludeLabelKey, ExcludeLabelValue)
+	if err != nil {
+		return err
+	}
+
+	now := time.Now().UTC()
+	nodeCreationTime := node.CreationTimestamp.UTC()
+	nodeAge := int(now.Sub(nodeCreationTime).Minutes())
+	if nodeAge <= NodeAgeCacheTTL {
+		log.Infof("Node younger than 90m was terminated, flushing DescribeTargetHealth caches")
```
Comment (davemasselink) [inline pkg/service/server.go]: could take advantage of formatting to include ttl const from above:
```suggestion
		log.Infof("Node younger than %v minutes was terminated, flushing DescribeTargetHealth caches", NodeAgeCacheTTL)
```

File: pkg/service/server.go [hunk 7]
```diff
@@ -427,51 +446,87 @@ func (mgr *Manager) drainLoadbalancerTarget(event *LifecycleEvent) error {
...
-				publishKubernetesEvent(kubeClient, newKubernetesEvent(EventReasonInstanceDeregisterFailed, msgFields, event.referencedNode.Name))
-				return
+		// sleep for random jitter per iteration
+		waitJitter(IterationJitterRangeSeconds)
+		log.Debugf("deregistering %v from %v (%v/%v)", instanceID, elbName, i+1, len(activeTargetGroups))
+		err = deregisterInstance(elbClient, elbName, instanceID)
+		if err != nil {
+			log.Info("deregister failed")
+			errChannel <- err
+			log.Info("after")
```
Comment (davemasselink) [inline pkg/service/server.go]: is this log line for debug purposes only or meant to remain in-place during use?

File: pkg/service/server.go [hunk 8]
```diff
@@ -427,51 +446,87 @@ func (mgr *Manager) drainLoadbalancerTarget(event *LifecycleEvent) error {
...
+	currentDeregistering := 0
+	for arn, port := range activeTargetGroups {
+
+		if event.eventCompleted {
+			return errors.New("event finished execution during deregistration")
+		}
+
+		currentDeregistering++
+		// sleep for random jitter per iteration
+		waitJitter(IterationJitterRangeSeconds)
```
Comment (davemasselink) [inline pkg/service/server.go]: anyway to move this mostly duplicated (with lines 466-483) code into a shared location and called with params as necessary?

File: cmd/serve.go [hunk 9]
```diff
@@ -141,27 +144,47 @@ func newKubernetesClient(localMode string) *kubernetes.Clientset {
...
 	config = config.WithCredentialsChainVerboseErrors(true)
 	config = request.WithRetryer(config, log.NewRetryLogger(DefaultRetryer))
 	sess, err := session.NewSession(config)
 	if err != nil {
 		log.Fatalf("failed to create elb client, %v", err)
 	}
-
+	cache.AddCaching(sess, cacheCfg)
+	cacheCfg.SetCacheTTL("elasticloadbalancing", "DescribeInstanceHealth", 180*time.Second)
+	cacheCfg.SetCacheTTL("elasticloadbalancing", "DescribeLoadBalancers", 300*time.Second)
```
Comment (davemasselink) [inline cmd/serve.go]: can 300 be extracted as a constant? esp if used in multiple places across files

Comment (davemasselink) [reply cmd/serve.go]: I think this was covered in @kevdowney's comment

File: pkg/service/elb.go (hunk 3 above)
Comment (eytan-avisror) [reply pkg/service/elb.go]: Not in this case because these are waiters iteration, so the count would be to timeout, not to completion.

File: pkg/service/elbv2.go (hunk 4 above)
Comment (eytan-avisror) [reply pkg/service/elbv2.go]: same

File: pkg/service/server.go (hunk 7 above)
Comment (eytan-avisror) [reply pkg/service/server.go]: good catch, removed it

File: pkg/service/server.go (hunk 8 above)
Comment (eytan-avisror) [reply pkg/service/server.go]: A bigger refactor is needed to move this code around, let's do this down the road.

**Comment by eytan-avisror** [comment]
Load tests seem good:

Screen Shot 2020-01-15 at 1 25 58 PM


with 500 TargetGroups
3 concurrent terminations took avg. 15 minutes
16 concurrent terminations took avg. 50 minutes
Pod running with limit of 1024MB memory did not have any restarts.
