### PR TITLE
Different drain timeout for Unknown nodes

### LINKED ISSUE #44: EC2 failures and graceful shutdown can cause prolonged errors
if EC2 failure occurs, and then the node is terminated by ASG or a person, the hook is received by lifecycle-manager and the drain/deregister flow will start.
In this case we will fail to drain for as long as `--drain-timeout`, this keeps the instance alive in the meanwhile and applications can see errors due to instance still being in target-groups.

We should evaluate whether we should try to deregister-only or skip alltogether when the node state is `unknown`

### PR DESCRIPTION
**Pull request by eytan-avisror**
Fixes #44 

This adds an option to drain nodes in Unknown state with a different timeout, or skip altogether.

### Testing
- [x] Reproduce Unknown node and initiate a terminate, verify timeout is honored
- [x] Test skip drain (e.g. set to 0)

### CODE REVIEW

File: pkg/service/server.go [hunk 1]
```diff
@@ -231,6 +234,11 @@ func (mgr *Manager) drainNodeTarget(event *LifecycleEvent) error {
 	metrics.IncGauge(DrainingInstancesCountMetric)
 	defer metrics.DecGauge(DrainingInstancesCountMetric)
 
+	if isNodeStatusInCondition(event.referencedNode, v1.ConditionUnknown) {
```
Comment (shrinandj) [inline pkg/service/server.go]: Can we add a unit test for this?

Comment (eytan-avisror) [reply pkg/service/server.go]: Done
