### PR TITLE
Prometheus metrics implementation

### LINKED ISSUE #10: Support  prometheus`/metrics` endpoint
we should add a `/metrics` api to the controller which will contain prometheus style metrics.
This can be then sent to various monitoring tools and provide metrics integration.

Interesting metrics:
- active-goroutines
- terminating-instances
- successful-lifecycle-events
- failed-lifecycle-events
- successful-node-drain
- failed-node-drain
- successful-deregister
- failed-deregister

### PR DESCRIPTION
**Pull request by eytan-avisror**
Fixes #10 

This PR adds the following metrics to /metrics endpoint:
```
# HELP process_active_goroutines indicates the current number of active goroutines.
# TYPE process_active_goroutines gauge
process_active_goroutines 6
# HELP process_average_duration_seconds indicates the average duration of processing a hook in seconds.
# TYPE process_average_duration_seconds gauge
process_average_duration_seconds 0
# HELP process_deregistering_instances_count indicates the current number of deregistering instances.
# TYPE process_deregistering_instances_count gauge
process_deregistering_instances_count 0
# HELP process_draining_instances_count indicates the current number of draining instances.
# TYPE process_draining_instances_count gauge
process_draining_instances_count 0
# HELP process_failed_events_total indicates the sum of all failed events.
# TYPE process_failed_events_total counter
process_failed_events_total 0
# HELP process_failed_lb_deregister_total indicates the sum of all events that failed to deregister loadbalancer.
# TYPE process_failed_lb_deregister_total counter
process_failed_lb_deregister_total 0
# HELP process_failed_node_drain_total indicates the sum of all events that failed to drain the node.
# TYPE process_failed_node_drain_total counter
process_failed_node_drain_total 0
# HELP process_rejected_events_total indicates the sum of all rejected events.
# TYPE process_rejected_events_total counter
process_rejected_events_total 0
# HELP process_successful_events_total indicates the sum of all successful events.
# TYPE process_successful_events_total counter
process_successful_events_total 0
# HELP process_successful_lb_deregister_total indicates the sum of all events that succeeded to deregister loadbalancer
# TYPE process_successful_lb_deregister_total counter
process_successful_lb_deregister_total 0
# HELP process_successful_node_drain_total indicates the sum of all events that succeeded to drain the node.
# TYPE process_successful_node_drain_total counter
process_successful_node_drain_total 0
# HELP process_terminating_instances_count indicates the current number of terminating instances.
# TYPE process_terminating_instances_count gauge
process_terminating_instances_count 0
```

### CODE REVIEW

File: pkg/service/metrics.go [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+	// MetricsEndpoint is the endpoint to expose for metrics
+	MetricsEndpoint = "/metrics"
+)
+
+func (m *MetricsServer) Start() {
+	m.Gauges = make(map[string]prometheus.Gauge, 0)
+	m.Counters = make(map[string]prometheus.Counter, 0)
+
+	gaugeIndex := map[string]string{
+		"active_goroutines":             "indicates the current number of active goroutines.",
```
Comment (sandeepbhojwani) [inline pkg/service/metrics.go]: make the key constant?

File: pkg/service/server.go [hunk 2]
```diff
@@ -77,20 +82,33 @@ func (mgr *Manager) Process(event *LifecycleEvent) error {
...
 
 func (mgr *Manager) AddEvent(event *LifecycleEvent) {
-	mgr.workQueueSync.Lock()
+	var (
+		metrics   = mgr.metrics
+		queueSync = mgr.workQueueSync
+	)
+	queueSync.Lock()
 	event.SetEventTimeStarted(time.Now())
+	metrics.IncGauge("terminating_instances_count")
```
Comment (sandeepbhojwani) [inline pkg/service/server.go]: add alb name as label/tag?

Comment (eytan-avisror) [reply pkg/service/server.go]: Good idea, created https://github.com/keikoproj/lifecycle-manager/issues/32 for doing this
